### ISSUE TITLE
Review:

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO29_Pudonnut_lintu.ruha#2]
### Mission:
 - [ ] 1. В заголовке миссии (в редукторе) -- указать версию миссии
 - [ ] 2. 
 - [ ] 3. 
 - [ ] 4. 
 - [ ] 5. 
 - [ ] 6. 
 - [ ] 7. 
 - [ ] 8. 

### tSF:
 - [ ] 1.  Почему? Раненых и беспатронных добивать? Как редеплои делать?
tSF_module_CCP = false;
tSF_module_FARP = false;
 - [ ] 2. 
 - [ ] 3. 
 - [ ] 4. 
 - [ ] 5. 
 - [ ] 6. 

### Dynai:
 - [ ] 1. В зоне реинф -- ,{ player inArea TRG1 }. Условие не сработает на выделенном сервере, т.к. на нем отсутствует player. Для того чтобы стригериться когда есть хоть один игрок в зоне, то используй чтото типа функции-примеры из missionConditions - https://github.com/rempopo/CO29_Pudonnut_lintu.ruha/blob/b21de0d3689bb656552c3ebe9b1bbb41051c709a/dzn_tSFramework/Modules/MissionConditions/Settings.sqf#L40-L41
 - [ ] 2. 
 - [ ] 3. 
 - [ ] 4. 
 - [ ] 5. 
 - [ ] 6. 

### Gear:
 - [ ] 1. Мож РХСные глоки? Они покрасивше
 - [ ] 2. Нет _random китов ни для одной из фракций!
 - [ ] 3. 
 - [ ] 4. 
 - [ ] 5. 
 - [ ] 6.

**Comment by Comrade333** [comment]
Mission:
 1.готово.
 2.
 3.
 4.
 5.
 6.
 7.
 8.
tSF:
 1. Т.к. опять ТЫЛАВАЯ АПЕРАЦИЯ, добавил слот медика, на стартовой точке есть ящики с медициной и боеприпасамию
 2.
 3.
 4.
 5.
 6.
Dynai:
 1. Исправил.
 2.
 3.
 4.
 5.
 6.
Gear:
 1. поменял на рхс.
 2. добавил для врагов
 3.
 4.
 5.
 6.
